# Copyright 2020-today  Numigi (tm) and all its contributors (https://bit.ly/numigiens)
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    "name": "Konvergo Mail Templates",
    "version": "16.0.1.0.0",
    "author": "Numigi",
    "maintainer": "Numigi",
    "license": "LGPL-3",
    "category": "Other",
    "summary": "Add custom mail templates for Konvergo",
    "depends": ["mail", "mail_template_fr_fields"],
    "data": [
        "templates/account_invoice.xml",
        "templates/account_payment.xml",
        "templates/calendar_attendee_invitation.xml",
        "templates/calendar_attendee_reminder.xml",
        "templates/calendar_attendee_updated.xml",
        "templates/hr_recruitment_acknowledgment.xml",
        "templates/hr_recruitment_interest.xml",
        "templates/hr_recruitment_refuse.xml",
        "templates/portal_new_user.xml",
        "templates/project_task_acknowledgment.xml",
        "templates/purchase_order.xml",
        "templates/purchase_rfq.xml",
        "templates/res_users_account_created.xml",
        "templates/res_users_reset_password.xml",
        "templates/res_users_set_password.xml",
        "templates/sale_order_cart_recovery.xml",
        "templates/sale_order_send_by_email.xml",
        "templates/survey_send_by_email.xml",
        "views/mail_template.xml",
        "views/menu.xml",
    ],
    "installable": True,
}
